[package]
name = "typify_startup"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
prettyplease = "0.2.36"
schemars = "0.8.22"
serde_json = "1.0.142"
syn = "2.0.104"
typify = "0.4.2"
